### PR TITLE
Adds 'context' parameter to k8s_object

### PR DESCRIPTION
**Pull request by jasongwartz**
This commit introduces a new parameter to k8s_object, in order
to manually specify the 'context' from the local kubeconfig file.
This is necessary in addition to the 'cluster' parameter in cases
where the bazel rule should be applied into a 'context' which is
configured on the local machine, but not currently selected.

### CODE REVIEW

**Comment by jasongwartz** [comment]
Making a PR into our own repo master branch first, to get the OK from @Globegitter - then we will configure our bazel repo to use the fork at master, and create the upstream PR.

**Comment by Globegitter** [comment]
Is this a breaking change now? What happens if the context is not passed in?

**Comment by jasongwartz** [comment]
In my testing, it behaves the same way as without the parameter (I believe because of the default value).

**Review by Globegitter — APPROVED** [review]
:chipmunk:

**Pull request merged**
